name: Publish Docker image
on:
  push:
    branches:
      - main
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [bionic, focal, groovy]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        env:
          DOCKER_IMAGE_TAG: docker.pkg.github.com/regolith-linux/regolith-deb-builder/regolith-deb-builder:${{ matrix.node }}
        run: |
          docker login -u ${{ github.actor }} -p ${{secrets.GITHUB_TOKEN}} docker.pkg.github.com
          docker build --build-arg=REFERENCE=ubuntu:${{ matrix.node }} -t ${DOCKER_IMAGE_TAG} .
          docker push ${DOCKER_IMAGE_TAG}
